title: My Portfolio
url: "https://robinrehn.github.io"
baseurl: "/portfolio"

# Minimal mistakes theme
remote_theme: mmistakes/minimal-mistakes

plugins: 
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Robin Rehn"
  avatar : "/assets/profile.png"
  bio    : "Data Analyst"
  skills:  
    - Python
    - SQL
    - Power BI
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/robin-rehn-b58a57108/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RobinRehn"

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        custom: custom/sidebar.html

# Build settings
markdown: kramdown
